---
upload-to-database:
  import:
    - import:
        dirpath: ./data/
        file_extension: csv 
        prefix_filename: sales
    - import:
        dirpath: ./data/
        file_extension: csv 
        prefix_filename: sensor_stock_levels
    - import:
        dirpath: ./data/
        file_extension: csv 
        prefix_filename: sensor_storage_temperature

cleaned-upload-to-database:
  import:
    - import:
        dirpath: ./data/
        file_extension: csv 
        prefix_filename: sales_processed
    - import:
        dirpath: ./data/
        file_extension: csv 
        prefix_filename: stock_processed
    - import:
        dirpath: ./data/
        file_extension: csv 
        prefix_filename: temp_processed

data_extraction:
  export:
    - export:
        host: s3
        bucket: 
        filename: 

modeling:
  export:
    - export:
        host: gsheet
        spread_sheet_id: 
        worksheet_name: Sheet1
